spring:
  datasource:
    url: jdbc:${POSTGRES_HOST:postgresql://localhost}:5432/evolution
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub